### ISSUE TITLE
Numbering in footnotes

### ISSUE THREAD

**Issue by zhampu** [sylvainjule/kirby-footnotes#5]
Hello Sylvain,
Great plugin!

I have a bug as the footnotes are being rendered  but the number of each is nor added to the LI( 1,23 etc) :

![Screenshot 2020-04-13 at 15 25 28](https://user-images.githubusercontent.com/10797660/79123726-14c3ca80-7d9b-11ea-8dd0-1add4a83aa27.png)

**Comment by sylvainjule** [comment]
Thank you!

This is the indended output, the list's numbering [should be achieved with CSS.](https://developer.mozilla.org/fr/docs/Web/HTML/Element/ol) 

Either with `list-style-type` or a custom counter:

```scss
ol {
    counter-reset: section;
    list-style-type: none;
    &:before {
        counter-increment: section;
        content: counters(section) '. ';
    }
}
```
